// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/devtron-labs/common-lib/monitoring"
	"github.com/devtron-labs/kubewatch/api/router"
	"github.com/devtron-labs/kubewatch/pkg/logger"
)

// Injectors from Wire.go:

func InitializeApp() (*App, error) {
	sugaredLogger := logger.NewSugaredLogger()
	monitoringRouter := monitoring.NewMonitoringRouter(sugaredLogger)
	routerImpl := api.NewRouter(sugaredLogger, monitoringRouter)
	app := NewApp(routerImpl, sugaredLogger)
	return app, nil
}
