// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/devtron-labs/kubewatch/api/router"
	"github.com/devtron-labs/kubewatch/internal/logger"
)

// Injectors from Wire.go:

func InitializeApp() (*App, error) {
	sugaredLogger, err := logger.NewSugardLogger()
	if err != nil {
		return nil, err
	}
	routerImpl := api.NewRouter(sugaredLogger)
	app := NewApp(routerImpl, sugaredLogger)
	return app, nil
}
